site_name: 'Alpha'
site_url: 'https://tgrx.github.io/alpha'
repo_url: 'https://github.com/tgrx/alpha'
site_author: 'Alexander Sidorov'

dev_addr: 'localhost:8000'
site_dir: '../.garbage/mkdocs/site/'

nav:
  - 'About': 'index.md'
  - 'Development':
      - 'Contributing': 'dev/contributing.md'
      - 'Commits, PRs': 'dev/pr.md'
      - 'Issues': 'dev/issues.md'
      - 'Versioning': 'dev/versioning.md'

theme:
  name: 'material'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - 'navigation.instant'
    - 'navigation.sections'
    - 'navigation.tabs'
    - 'navigation.tracking'
