default:
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES: [ ]
  HOST: ""
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  HOST: "localhost"
  PORT: 8000


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2
