default:
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES: [ ]
  HEROKU_API_APP_ID: ""
  HEROKU_API_TOKEN: ""
  HOST: ""
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  REQUEST_TTL: 0
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  HOST: "localhost"
  PORT: 8000
  REQUEST_TTL: 300


ci:
  HOST: "localhost"
  PORT: 8000
  REQUEST_TTL: 100
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2


heroku:
  MODE_DEBUG: false
  REQUEST_TTL: 10
  VENV_SYNTHETIC: 1


docker:
  MODE_DEBUG: false
  REQUEST_TTL: 10

