site_name: 'Alpha'
site_url: 'https://tgrx.github.io/alpha'
repo_url: 'https://github.com/tgrx/alpha'
site_author: 'Alexander Sidorov'

dev_addr: 'localhost:8000'
site_dir: '../.garbage/mkdocs/site/'

nav:
  - 'About': 'index.md'
  - 'Development':
    - 'Contributing': 'dev/contributing.md'
    - 'Issues': 'dev/issues.md'
    - 'Commits, PRs': 'dev/pr.md'
    - 'Versioning': 'dev/versioning.md'

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'green'
  features:
    - 'navigation.instant'
    - 'navigation.tracking'
    - 'navigation.tabs'
    - 'navigation.sections'
