name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  heroku:
    if: github.actor == 'tgrx'
    name: ðŸ’¾ Image is deployed to Heroku.
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Code is pulled from repo.
        uses: actions/checkout@v3
      - name: ðŸ’¾ Image is deployed to Heroku.
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "main"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alphasrv"
          heroku_email: "alexander@sidorov.dev"
