name: Deployment

on:
  workflow_dispatch:

jobs:
  docker:
    if: github.actor == 'tgrx'
    name: ğŸ’¾ Image is deployed to DockerHub.
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Code is pulled from repo.
        uses: actions/checkout@v3
      - name: âš™ï¸ QEMU is set up.
        uses: docker/setup-qemu-action@v2
      - name: âš™ï¸ Docker BuildX is set up.
        uses: docker/setup-buildx-action@v2
      - name: ğŸ”‘ Job is logged in DockerHub.
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: ğŸ“ Build arguments are configured.
        id: build-args
        run: |
          echo ::set-output name=python_version::$(cat .python-version)
          echo ::set-output name=version::$(cat version.txt)
      - name: ğŸ’¾ Image is deployed to DockerHub.
        uses: docker/build-push-action@v3
        with:
          build-args: |
            python_version=${{ steps.build-args.outputs.python_version }}
            version=${{ steps.build-args.outputs.version }}
          context: .
          push: true
          tags: |
            alexandersidorov/alpha:${{ steps.build-args.outputs.version }}
            alexandersidorov/alpha:latest
  heroku:
    name: ğŸ’¾ Image is deployed to Heroku.
    needs:
      - docker
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Code is pulled from repo.
        uses: actions/checkout@v3
      - name: ğŸ’¾ Image is deployed to Heroku.
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "main"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alphasrv"
          heroku_email: "alexander@sidorov.dev"
