name: QA

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CACHE_CUSTOM_KEY: 0
  DATABASE_URL: "postgres://ci:ci@localhost:5432/ci?sslmode=disable"
  PGPASSFILE: config/.pgpass
  POETRY_VIRTUALENVS_CREATE: false
  POETRY_VIRTUALENVS_IN_PROJECT: false
  PYTHONPATH: "src"
  TEST_SERVICE_URL: "http://localhost:8000"

jobs:
  code-lint:
    name: 游끥 Linters approve code.
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - 3.10.10
    runs-on: ${{ matrix.os }}

  build:
    name: 游닍 Package is built.
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.10.10
    runs-on: ${{ matrix.os }}
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
      python-location: ${{ env.pythonLocation }}
      python-version: ${{ matrix.python-version }}
      runs-on: ${{ matrix.os }}
    steps:
      - name: 游닌 Code is pulled from repo.
        uses: actions/checkout@v2
      - name: 游냀 Python runtime is set up.
        uses: actions/setup-python@v2
        with:
          architecture: 'x64'
          python-version: ${{ matrix.python-version }}
      - name: 游댐 Runtime cache key is calculated.
        id: cache-key
        run: |
          echo "::set-output name=value::cache-runtime-${{ matrix.os }}-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}-${{ env.CACHE_CUSTOM_KEY }}"
      - name: 游닍 Runtime is cached and restored.
        id: cache-runtime
        uses: actions/cache@v2
        with:
          key: ${{ steps.cache-key.outputs.value }}
          path: ${{ env.pythonLocation }}
      - name: 游댋 Poetry is installed.
        if: ${{ !steps.cache-runtime.outputs.cache-hit }}
        run: |
          pip install pipx
          pipx install poetry
      - name: 游댊 Dependencies are installed.
        if: ${{ !steps.cache-runtime.outputs.cache-hit }}
        run: |
          poetry export --dev --format=requirements.txt --output=requirements.txt --without-hashes
          pip install --requirement requirements.txt
  run-tests:
    name: 驕勇 Tests are passed.
    needs:
      - build
    runs-on: ${{ needs.build.outputs.runs-on }}
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s
        env:
          POSTGRES_DB: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_USER: ci
    steps:
      - name: 游닌 Code is pulled from repo.
        uses: actions/checkout@v2
      - name: 游냀 Python runtime is set up.
        uses: actions/setup-python@v2
        with:
          architecture: 'x64'
          python-version: ${{ needs.build.outputs.python-version }}
      - name: 游닍 Runtime is restored from cache.
        id: restore-build
        uses: actions/cache@v2
        with:
          key: ${{ needs.build.outputs.cache-key }}
          path: ${{ needs.build.outputs.python-location }}
      - name: 游뿥 DB and release steps are performed.
        if: ${{ steps.restore-build.outputs.cache-hit }}
        run: |
          chmod 0600 config/.pgpass
          make initdb release
      - name: 游 Web server is up.
        if: ${{ steps.restore-build.outputs.cache-hit }}
        run: make run-prod &
      - name: 驕勇 Tests are passed.
        if: ${{ steps.restore-build.outputs.cache-hit }}
        run: make tests coverage
  check-code-typing:
    name: 驕勇 Code typing checks are passed.
    needs:
      - build
    runs-on: ${{ needs.build.outputs.runs-on }}
    steps:
      - name: 游닌 Code is pulled from repo.
        uses: actions/checkout@v2
      - name: 游냀 Python runtime is set up.
        uses: actions/setup-python@v2
        with:
          architecture: 'x64'
          python-version: ${{ needs.build.outputs.python-version }}
      - name: 游닍 Runtime is restored from cache.
        id: restore-build
        uses: actions/cache@v2
        with:
          key: ${{ needs.build.outputs.cache-key }}
          path: ${{ needs.build.outputs.python-location }}
      - name: 驕勇 Code typing checks are passed.
        if: ${{ steps.restore-build.outputs.cache-hit }}
        run: make code-typing
  check-code-format:
    name: 驕勇 Code format checks are passed.
    needs:
      - build
    runs-on: ${{ needs.build.outputs.runs-on }}
    steps:
      - name: 游닌 Code is pulled from repo.
        uses: actions/checkout@v2
      - name: 游냀 Python runtime is set up.
        uses: actions/setup-python@v2
        with:
          architecture: 'x64'
          python-version: ${{ needs.build.outputs.python-version }}
      - name: 游닍 Runtime is restored from cache.
        id: restore-build
        uses: actions/cache@v2
        with:
          key: ${{ needs.build.outputs.cache-key }}
          path: ${{ needs.build.outputs.python-location }}
      - name: 驕勇 Code format checks are passed.
        if: ${{ steps.restore-build.outputs.cache-hit }}
        run: make code-format
  run-code-linters:
    name: 驕勇 Linters approve the code.
    needs:
      - build
    runs-on: ${{ needs.build.outputs.runs-on }}
    steps:
      - name: 游닌 Code is pulled from repo.
        uses: actions/checkout@v2
      - name: 游냀 Python runtime is set up.
        uses: actions/setup-python@v2
        with:
          architecture: 'x64'
          python-version: ${{ needs.build.outputs.python-version }}
      - name: 游닍 Runtime is restored from cache.
        id: restore-build
        uses: actions/cache@v2
        with:
          key: ${{ needs.build.outputs.cache-key }}
          path: ${{ needs.build.outputs.python-location }}
      - name: 驕勇 Linters approve the code.
        if: ${{ steps.restore-build.outputs.cache-hit }}
        run: make code-linters
