name: Webapp - Dev - ðŸ§

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  CACHE_CUSTOM_KEY: 0


jobs:
  toolchain:
    name: ðŸ› ï¸ Toolchain is built.

    runs-on: ubuntu-latest

    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}

    steps:
      - name: ðŸ“¥ Code is pulled from repo.
        uses: actions/checkout@v3

      - name: ðŸ”‘ Cache key is calculated.
        id: cache-key
        run: |
          echo "value=cache-toolchain-ubuntu-${{ hashFiles('services/webapp/poetry.lock', 'services/webapp/.poetry-version', 'services/webapp/.python-version') }}-${{ env.CACHE_CUSTOM_KEY }}" >> $GITHUB_OUTPUT
      - name: ðŸ“¦ Toolchain is cached and restored.
        id: cache-toolchain
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache-key.outputs.value }}
          path: |
            .local
            services/webapp/.local

      - name: ðŸ§© Envs are set up.
        run: |
          echo "${GITHUB_WORKSPACE}/.github/bin" >> ${GITHUB_PATH}
          echo "${GITHUB_WORKSPACE}/.local/pyenv/bin" >> ${GITHUB_PATH}
          echo "PYENV_ROOT=${GITHUB_WORKSPACE}/.local/pyenv" >> ${GITHUB_ENV}

      - name: ðŸ Pyenv is installed.
        if: ${{ !steps.cache-toolchain.outputs.cache-hit }}
        run: |
          curl https://pyenv.run | bash
          eval "$(pyenv init --path)"

      - name: ðŸ Pyenv is rehashed.
        run: |
          echo "$(pyenv root)/shims" >> ${GITHUB_PATH}
          pyenv rehash

      - name: ðŸ›‚ Checkpoint.
        run: |
          echo ${PATH}
          echo "# ~~~~ task ~~~~"
          which task
          task --version
          echo "# ~~~~ pyenv ~~~~"
          which pyenv
          pyenv --version
          echo "# ~~~~ python ~~~~"
          which python
          python --version
          echo "# ~~~~ shims ~~~~"
          echo "$(pyenv root)/shims"
          ls -la "$(pyenv root)/shims"

      - name: ðŸ› ï¸ Developer toolchain is set.
        run: |
          task
          poetry env info
        working-directory: services/webapp/

  tests:
    name: ðŸ›‚ Tests are passed.

    needs:
      - toolchain

    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Code is pulled from repo.
        uses: actions/checkout@v3

      - name: ðŸ“¦ Toolchain is restored from cache.
        id: restore-toolchain
        uses: actions/cache@v3
        with:
          fail-on-cache-miss: true
          key: ${{ needs.toolchain.outputs.cache-key }}
          path: |
            .local
            services/webapp/.local

      - name: ðŸ§© Envs are set up.
        id: env-setup
        run: |
          echo "$GITHUB_WORKSPACE/.github/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/.local/pyenv/bin" >> ${GITHUB_PATH}
          echo "PYENV_ROOT=${GITHUB_WORKSPACE}/.local/pyenv" >> ${GITHUB_ENV}

      - name: ðŸ Pyenv is rehashed.
        run: |
          echo "$(pyenv root)/shims" >> ${GITHUB_PATH}
          pyenv rehash

      - name: ðŸš€ Web server is up.
        run: task run-server-dev &
        working-directory: services/webapp/

      - name: ðŸ›‚ Unit tests are passed.
        run: |
          task run-tests-coverage
        working-directory: services/webapp/

  linters:
    name: ðŸ›‚ Linters approve code.

    needs:
      - toolchain

    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Code is pulled from repo.
        uses: actions/checkout@v3

      - name: ðŸ“¦ Toolchain is restored from cache.
        id: restore-toolchain
        uses: actions/cache@v3
        with:
          fail-on-cache-miss: true
          key: ${{ needs.toolchain.outputs.cache-key }}
          path: |
            .local
            services/webapp/.local

      - name: ðŸ§© Envs are set up.
        id: env-setup
        run: |
          echo "$GITHUB_WORKSPACE/.github/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/.local/pyenv/bin" >> ${GITHUB_PATH}
          echo "PYENV_ROOT=${GITHUB_WORKSPACE}/.local/pyenv" >> ${GITHUB_ENV}

      - name: ðŸ Pyenv is rehashed.
        run: |
          echo "$(pyenv root)/shims" >> ${GITHUB_PATH}
          pyenv rehash

      - name: ðŸ›‚ Linters approve code.
        run: task code-lint
        working-directory: services/webapp/
